framework:
  messenger:
    transports:
      async: '%env(MESSENGER_TRANSPORT_DSN)%'
      failed: '%env(MESSENGER_TRANSPORT_DSN)%'
    routing:
      App\Message\Search: async
      App\Message\LastMinute: async
