version: "3.7"

services:
  backend:
    image: sf_travel
    build:
      context: ./..
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - ${APP_EXPOSED_PORT}:80
    volumes:
      - ./../:/var/www/html
      - ./backend/config/vhosts:/etc/apache2/sites-enabled
      - ./backend/config/dir/dir.conf:/etc/apache2/mods-enabled/dir.conf
      - ./backend/config/xdebug/xdebug.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    extra_hosts:
      - "host.docker.internal:host-gateway"
  queue-worker:
    image: sf_travel
    networks:
      - app-network
    command: ./bin/console messenger:consume async -vvv
    depends_on:
      - queuer
    restart: always
  queuer:
    image: rabbitmq:3.9.5
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${DATABASE_USER}
      RABBITMQ_DEFAULT_PASS: ${DATABASE_PASSWORD}
    networks:
      - app-network
  database:
    image: postgres:15.1
    ports:
      - ${DATABASE_EXPOSED_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - app-network
  selenium-hub:
    image: selenium/hub:4.4.0
    depends_on:
      - backend
    ports:
      - "127.0.0.1:4442:4442"
      - "127.0.0.1:4443:4443"
      - "127.0.0.1:4444:4444"
    networks:
      - app-network
  chrome:
    image: selenium/node-chrome:105.0-20220831
    shm_size: 2gb
    depends_on:
      - selenium-hub
      - backend
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "127.0.0.1:6900:5900"
    networks:
      - app-network

volumes:
  postgres:
    driver: local

networks:
  app-network:
    driver: bridge
