parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $optionalTrips: !tagged_iterator 'app.crawler.optional_trips'
      $pageAttractions: !tagged_iterator 'app.crawler.page_attractions'
      $hotels: !tagged_iterator 'app.crawler.hotels'
  _instanceof:
    App\Utils\Crawler\OptionalTrip\OptionalTripInterface:
      tags: [ name: 'app.crawler.optional_trips' ]
      public: true
    App\Utils\Crawler\PageAttraction\PageAttractionInterface:
      tags: [ name: 'app.crawler.page_attractions' ]
      public: true
    App\Utils\Crawler\Hotel\HotelInterface:
      tags: [ name: 'app.crawler.hotels' ]
      public: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/**/Model'
      - '../src/**/Input'
      - '../src/**/Mocks'

  Symfony\Component\Panther\Client:
    factory: [ App\Factory\SeleniumClient, 'create' ]
    arguments:
      $seleniumUrl: '%env(SELENIUM_URL)%'
