parameters:
  deepl.key: '%env(DEEPL_KEY)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $projectDir: '%kernel.project_dir%'
      $optionalTrips: !tagged_iterator 'app.crawler.optional_trips'
      $pageAttractions: !tagged_iterator 'app.crawler.page_attractions'
      $hotels: !tagged_iterator 'app.crawler.hotels'
      $flights: !tagged_iterator 'app.crawler.flights'
      $weathers: !tagged_iterator 'app.api.weather'
  _instanceof:
    App\Utils\Crawler\OptionalTrip\OptionalTripInterface:
      tags: [ name: 'app.crawler.optional_trips' ]
      public: true
    App\Utils\Crawler\PageAttraction\PageAttractionInterface:
      tags: [ name: 'app.crawler.page_attractions' ]
      public: true
    App\Utils\Crawler\Hotel\HotelInterface:
      tags: [ name: 'app.crawler.hotels' ]
      public: true
    App\Utils\Crawler\Flight\FlightInterface:
      tags: [ name: 'app.crawler.flights' ]
      public: true
    App\Utils\Api\Weather\WeatherInterface:
      tags: [ name: 'app.api.weather' ]
      public: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/**/Model'
      - '../src/**/Input'
      - '../src/**/Mocks'

  Symfony\Component\Panther\Client:
    factory: [ App\Factory\SeleniumClient, 'create' ]
    arguments:
      $seleniumUrl: '%env(SELENIUM_URL)%'

  App\Utils\Api\Translation\DeepL:
    arguments: [ '%deepl.key%' ]
