parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $optionalTrips: !tagged_iterator 'app.crawler.optional_trips'
  _instanceof:
    App\Utils\Crawler\OptionalTrip\OptionalTripInterface:
      tags: [ name: 'app.crawler.optional_trips' ]
      public: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/**/Model'

  Symfony\Component\Panther\Client:
    factory: [ App\Factory\SeleniumClient, 'create' ]
    arguments:
      $seleniumUrl: '%env(SELENIUM_URL)%'
